### ISSUE TITLE
회원가입 백엔드 로직 제작 (이메일 인증)

### ISSUE THREAD

**Issue by Paul-scpark** [Paul-scpark/Data-planet#41]
- 회원가입에 필요한 정보 입력 후, DB INSERT (POST API)
- 이메일 인증
- 아이디 중복 확인
- 이메일 해쉬 처리 (bcrypt)
- jwt 토큰 발급

**Comment by Paul-scpark** [comment]
@ireneyoungaha 이메일 인증 관련 링크 공유 부탁드립니다 :)

**Comment by ireneyoungaha** [comment]
https://www.javatpoint.com/django-user-registration-with-email-confirmation
 입니다!
