### ISSUE TITLE
T5, KoBigBird 모델 조사

### ISSUE THREAD

**Issue by Paul-scpark** [Paul-scpark/Data-planet#68]

**Comment by kkeunbyeol** [comment]
- 목적: 경량화 모델 적용을 위해 DistillBERT를 적용해 보기로 했고, 추가로 T5나 BigBird 중 더욱 적합한 알고리즘을 사용하기 위함

- T5: seq2seq 모델로 현재 프로젝트에서 이용되는 카테고리 분류에 최적이라고 할 수 없음.
- BigBird: BERT 기반 트랜스포머로 카테고리 분류에 적합하다고 볼 수 있음. 그러나 BigBird의 긴 시퀀스에서 유리하다는 장점을 이용하기에는 우리 프로젝트의 시퀀스가 그만큼 길지 않음.
   [https://huggingface.co/docs/transformers/model_doc/big_bird]
--------------------------------------------------------------------------------------------------

 https://paperswithcode.com/sota/text-classification-on-klue
 https://github.com/monologg/KoBigBird
![image](https://user-images.githubusercontent.com/86813592/215773592-5fa21167-0eb9-4d43-9695-4b9f63281305.png)

 위의 자료들(NCMS, YNAT과 같은 텍스트 분류 과제에서 RoBERTa가 상위권에 위치함)을 참고하여 RoBERTa를 적용해보는 것이 좋다고 판단함
RoBERTa: BERT에서 hyper parameter들을 조정하여 성능을 높이는 방법

DistillBERT - 이상암 / RoBERTa - 고은별 나눠서 테스트 진행
